name: GitHub Actions - Databricks demo
on: [push]

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:

  db_demo:
    runs-on: ubuntu-latest
    steps:

    - name: install databricks-cli
      run: |
        pip install databricks-cli

    - name: checkout
      uses: actions/checkout@v3

    - name: create job
      id: create_job
      run: |
        JOB_OUT=$(databricks jobs create --json-file jobSpec.json)
        JOB_ID=$(echo $JOB_OUT | jq '.job_id')
        echo "::set-output name=jobs_id::$JOB_ID"

    - name: run workflow
      run: |
        databricks jobs run-now --job-id ${{ steps.create_job.outputs.jobs_id }}

    

